In [53]:
import numpy as np
import random

### Creando listas aleatórias com NUMPY

##### Para que isso seja possível temos que baixar a biblioteca RANDOM para criar um gerador (rng) e a partir dele gerar nossas lista aleatórios, que obedecerão os parâmetros fornecidos, onde poderemos realizar nossas análises.

In [54]:
rng = np.random.default_rng()
print(rng)

Generator(PCG64)


In [55]:
rng = np.random.default_rng(seed=42)
valor_unitario = rng.integers(low=30, high=50, size=7 )
print(valor_unitario)

[31 45 43 38 38 47 31]


In [56]:
rng = np.random.default_rng(seed=42)
qtde_vendida = rng.integers(low=100, high=500, size=7 )
print(qtde_vendida)

[135 409 361 275 273 443 134]


In [57]:
print('Valor unitário de cada item')
print(valor_unitario)
print('Quantidade vendida de cada item em um dia')
print(qtde_vendida)

print(f'O faturamento total de 01 semana foi de R$ {np.dot(qtde_vendida, valor_unitario):,.2f}')

Valor unitário de cada item
[31 45 43 38 38 47 31]
Quantidade vendida de cada item em um dia
[135 409 361 275 273 443 134]
O faturamento total de 01 semana foi de R$ 83,912.00
